### ISSUE TITLE
Why did you first load resnet 50 weights and then load the pretrained tensorflow model? Did the latter override the parameters?

### ISSUE THREAD

**Issue by hypercost** [XPFly1989/FCRN#1]
https://github.com/XPFly1989/FCRN/blob/master/train.py#L72

https://github.com/XPFly1989/FCRN/blob/master/train.py#L77

**Comment by hypercost** [comment]
I see. The renet-50 weights seems not be in use.
I have trained 50 epoch, but the results is not good.


![gt_depth_epoch_50.png](https://i.loli.net/2018/07/19/5b5054682eecd.png)


![gt_depth_input_rgb_epoch_50.png](https://i.loli.net/2018/07/19/5b505468577cb.png)


![pred_depth_epoch_50.png](https://i.loli.net/2018/07/19/5b50546859365.png)

**Comment by XPFly1989** [comment]
Yeah，the resnet-50 weights didn't work well，so it is commented out but not deleted.

**Comment by sanweiliti** [comment]
Hi, @XPFly1989 
Do you know why the resnet50 weights didn't work well? I'm also trying to train the fcrn model from scratch, and I think the author initialized the parameters from pretrained resnet50 weights, so it should work well if everything else is okay.

**Comment by XPFly1989** [comment]
> Hi, @XPFly1989
> Do you know why the resnet50 weights didn't work well? I'm also trying to train the fcrn model from scratch, and I think the author initialized the parameters from pretrained resnet50 weights, so it should work well if everything else is okay.

You are right. Because the training data I used is very limited, but the data what the author used is far more than these. And train the model from scratch is very skilful，I don't have much experience.
